---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


# Basics
- name: Update APT package cache
  action: apt update_cache=yes

- name: Run apt-get upgrade
  action: apt upgrade=yes
  poll: 15

# Alternate Admin Account
- name: Add Alternate Admin User
  action: user name="{{ alt_admin_name }}" password="{{ alt_admin_password }}"

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add alt admin user to sudoers
  action: lineinfile dest=/etc/sudoers regexp="{{ alt_admin_name }} ALL" line="{{ alt_admin_name }} ALL=(ALL) ALL" state=present

# Fail2Ban
- include: fail2ban-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes

# SSH
- include: ssh.yml

# Autoupdate
- include: autoupdate-Debian.yml
  when: ansible_os_family == 'Debian' and security_autoupdate_enabled

# Logwatch
- include: logwatch-Debian.yml
  when: ansible_os_family == 'Debian'
